title: ROB 498 - Final Project
description: We will be discussing our final project findings
theme: just-the-docs

url: https://sarahtj.github.io/Vitpose_Extension

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
